// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

import {
  nsHarborPreloadedFeature,
  nsHarborMultiWindowFeature,
} from "chrome://browser/content/harbor-components/HarborCommonUtils.mjs";

const DOT_RE = /\./g;
const WHITESPACE_RE = /\s/g;
const NON_NAME_RE = /[^A-Za-z_-]+/g;
const MOD_ID_RE = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;

// The mod store shipped with the browser. "harbor.mods.store-url" can point
// at a remote store with the same layout instead:
//   {store}/index.json            - { "mods": [{ id, name, description, ... }] }
//   {store}/mods/{id}/theme.json  - the mod manifest
const BUNDLED_STORE_URL = "chrome://browser/content/harbor-mods-store";
const MOD_ASSET_KEYS = ["style", "readme", "preferences", "image"];

/**
 * Harbor Mods Manager, handles downloading, updating and applying Harbor Mods.
 *
 * @augments nsHarborPreloadedFeature
 */
class nsHarborMods extends nsHarborPreloadedFeature {
  // private properties start
  #kHarborStylesheetModHeader = "/* Harbor Mods - Generated by HarborMods.";
  #kHarborStylesheetModHeaderBody = `* DO NOT EDIT THIS FILE DIRECTLY!
* Your changes will be overwritten.
* Instead, go to the preferences and edit the mods there.
*/
`;
  #kHarborStylesheetModFooter = `
/* End of Harbor Mods */
`;
  #getCurrentDateTime = () =>
    new Intl.DateTimeFormat("en-US", {
      dateStyle: "full",
      timeStyle: "full",
    }).format(new Date().getTime());

  constructor() {
    super();
  }

  // Stylesheet service
  #_modsBackend = null;

  get #modsBackend() {
    if (!this.#_modsBackend) {
      this.#_modsBackend = Cc["@mozilla.org/harbor/mods-backend;1"].getService(
        Ci.nsIHarborModsBackend
      );
    }
    return this.#_modsBackend;
  }

  get #styleSheetPath() {
    return PathUtils.join(PathUtils.profileDir, "chrome", "harbor-themes.css");
  }

  async #handleDisableMods() {
    await this.#rebuildModsStylesheet();
  }

  #getStylesheetPathForMod(mod) {
    return PathUtils.join(this.getModFolder(mod.id), "chrome.css");
  }

  async #readStylesheet() {
    const path = this.modsRootPath;
    if (!(await IOUtils.exists(path))) {
      return "";
    }
    return await IOUtils.readUTF8(this.#styleSheetPath);
  }

  async #insertStylesheet() {
    try {
      const content = await this.#readStylesheet();
      this.#modsBackend.rebuildModsStyles(content);
    } catch (e) {
      console.warn("[HarborMods]: Error rebuilding mods styles:", e);
    }
  }

  async #rebuildModsStylesheet() {
    const mods = await this.#getEnabledMods();

    await this.#writeStylesheet(mods);

    const modsWithPreferences = await Promise.all(
      mods.map(async mod => {
        const preferences = await this.getModPreferences(mod);

        return {
          name: mod.name,
          enabled: mod.enabled,
          preferences,
        };
      })
    );

    this.#setDefaults(modsWithPreferences);
    this.#writeToDom(modsWithPreferences);

    await this.#insertStylesheet();
  }

  async #getEnabledMods() {
    if (Services.prefs.getBoolPref("harbor.themes.disable-all", false)) {
      // eslint-disable-next-line no-console
      console.info("[HarborMods]: Mods are disabled by user preference.");
      return [];
    }
    const modsObject = await this.getMods();
    const mods = Object.values(modsObject).filter(
      mod => mod.enabled === undefined || mod.enabled
    );

    // eslint-disable-next-line no-shadow
    const modList = mods.map(({ name }) => name).join(", ");

    const message =
      modList !== ""
        ? `[HarborMods]: Loading enabled Harbor mods: ${modList}.`
        : "[HarborMods]: No enabled Harbor mods.";

    console.warn(message);

    return mods;
  }

  #setDefaults(modsWithPreferences) {
    for (const { preferences, enabled } of modsWithPreferences) {
      if (enabled !== undefined && !enabled) {
        continue;
      }

      for (const { type, property, defaultValue } of preferences) {
        if (defaultValue === undefined) {
          continue;
        }

        const getProperty =
          type === "checkbox"
            ? Services.prefs.getBoolPref
            : Services.prefs.getStringPref;
        const setProperty =
          type === "checkbox"
            ? Services.prefs.setBoolPref
            : Services.prefs.setStringPref;

        try {
          getProperty(property);
        } catch {
          console.warn(
            `[HarborMods]: Setting default value for ${property} to ${defaultValue} (${typeof defaultValue})`
          );

          if (
            typeof defaultValue !== "boolean" &&
            typeof defaultValue !== "string" &&
            typeof defaultValue !== "number"
          ) {
            console.warn(
              `[HarborMods]: Warning, invalid data type received (${typeof defaultValue}), skipping.`
            );
            continue;
          }

          setProperty(
            property,
            typeof defaultValue === "boolean"
              ? defaultValue
              : defaultValue.toString()
          );
        }
      }
    }
  }

  #writeToDom(modsWithPreferences) {
    // Precompute per-mod data once; values are global prefs and sanitized
    // names don't vary per browser window, so this hoists O(windows) work.
    const prepared = modsWithPreferences.map(
      // eslint-disable-next-line no-shadow
      ({ enabled, preferences, name }) => ({
        enabled,
        sanitizedName: this.sanitizeModName(name),
        prefs: preferences.map(({ property, type }) => {
          const isEnabled = enabled === undefined || enabled;
          const getPref =
            type === "checkbox"
              ? Services.prefs.getBoolPref
              : Services.prefs.getStringPref;
          const fallback = type === "checkbox" ? false : "";

          return {
            property,
            type,
            sanitizedProperty: property?.replaceAll(DOT_RE, "-"),
            value: isEnabled ? getPref(property, fallback) : fallback,
          };
        }),
      })
    );

    for (const browser of nsHarborMultiWindowFeature.browsers) {
      const doc = browser.document;
      const root = doc.documentElement;

      for (const { enabled, sanitizedName, prefs } of prepared) {
        if (enabled !== undefined && !enabled) {
          const element = doc.getElementById(sanitizedName);
          if (element) {
            element.remove();
          }

          for (const { type, sanitizedProperty } of prefs) {
            if (type === "checkbox") {
              continue;
            }
            root.style.removeProperty(`--${sanitizedProperty}`);
          }

          continue;
        }

        for (const { type, sanitizedProperty, value } of prefs) {
          switch (type) {
            case "dropdown": {
              if (value !== "") {
                let element = doc.getElementById(sanitizedName);

                if (!element) {
                  element = doc.createElement("div");
                  element.style.display = "none";
                  element.setAttribute("id", sanitizedName);
                  doc.body.appendChild(element);
                }

                element.setAttribute(sanitizedProperty, value);
              }
              break;
            }

            case "string": {
              if (value === "") {
                root.style.removeProperty(`--${sanitizedProperty}`);
              } else {
                root.style.setProperty(`--${sanitizedProperty}`, value);
              }
              break;
            }
          }
        }
      }
    }
  }

  async #writeStylesheet(modList = []) {
    const mods = [];

    for (let mod of modList) {
      mod._filePath = this.#getStylesheetPathForMod(mod);
      mods.push(mod);
    }

    let content = this.#kHarborStylesheetModHeader;
    content += `\n* FILE GENERATED AT: ${this.#getCurrentDateTime()}\n`;
    content += this.#kHarborStylesheetModHeaderBody;

    for (let mod of mods) {
      if (mod.enabled !== undefined && !mod.enabled) {
        continue;
      }

      content += `\n/* Name: ${mod.name} */\n`;
      content += `/* Description: ${mod.description} */\n`;
      content += `/* Author: @${mod.author} */\n`;

      if (mod._readmeURL) {
        content += `/* Readme: ${mod.readme} */\n`;
      }

      const chromeContent = await IOUtils.readUTF8(mod._filePath);
      content += chromeContent;
    }

    content += this.#kHarborStylesheetModFooter;

    const buffer = new TextEncoder().encode(content);

    await IOUtils.write(this.#styleSheetPath, buffer);
  }

  #compareVersions(version1, version2) {
    let result = false;

    if (typeof version1 !== "object") {
      version1 = version1.toString().split(".");
    }

    if (typeof version2 !== "object") {
      version2 = version2.toString().split(".");
    }

    for (let i = 0; i < Math.max(version1.length, version2.length); i++) {
      if (version1[i] == undefined) {
        version1[i] = 0;
      }
      if (version2[i] == undefined) {
        version2[i] = 0;
      }
      if (Number(version1[i]) < Number(version2[i])) {
        result = true;
        break;
      }
      if (version1[i] != version2[i]) {
        break;
      }
    }
    return result;
  }

  #composeModApiUrl(modId) {
    // The id ends up in a URL and in a profile path, keep it to a plain slug.
    if (!MOD_ID_RE.test(modId ?? "")) {
      throw new Error(`[HarborMods]: Invalid mod id: ${modId}`);
    }
    return `${this.storeBaseUrl}/mods/${modId}/theme.json`;
  }

  #isAllowedStoreUrl(url) {
    let parsed;
    try {
      parsed = new URL(url);
    } catch {
      return false;
    }
    // Either the store shipped inside the browser, or a remote one over
    // HTTPS. Without a signing/hash scheme this is the minimum guard against
    // MITM or a store-hosted HTTP redirect serving attacker-controlled
    // CSS/JSON into the chrome profile.
    return (
      parsed.protocol === "https:" || url.startsWith(`${BUNDLED_STORE_URL}/`)
    );
  }

  async #downloadUrlToFile(url, path, maxRetries = 3, retryDelayMs = 500) {
    if (!this.#isAllowedStoreUrl(url)) {
      throw new Error(`[HarborMods]: Refusing mod asset URL: ${url}`);
    }

    let attempt = 0;

    while (attempt < maxRetries) {
      try {
        const response = await fetch(url);

        if (!response.ok) {
          throw new Error(
            `HTTP error! status: ${response.status} for url: ${url}`
          );
        }

        const data = await response.text();

        // convert the data into a Uint8Array
        const buffer = new TextEncoder().encode(data);
        await IOUtils.write(path, buffer);

        return; // to exit the loop
      } catch (e) {
        attempt++;
        if (attempt >= maxRetries) {
          console.error(
            "[HarborMods]: Error downloading file after retries",
            url,
            e
          );
        } else {
          console.warn(
            `[HarborMods]: Download failed (attempt ${attempt} of ${maxRetries}), retrying in ${retryDelayMs}ms...`,
            url,
            e
          );
          await new Promise(res => setTimeout(res, retryDelayMs));
        }
      }
    }
  }

  // private properties end

  // public properties start

  throttle(mainFunction, delay) {
    let timerFlag = null;

    return (...args) => {
      if (timerFlag === null) {
        mainFunction(...args);
        timerFlag = setTimeout(() => {
          timerFlag = null;
        }, delay);
      }
    };
  }

  debounce(mainFunction, wait) {
    let timerFlag;

    return (...args) => {
      clearTimeout(timerFlag);
      timerFlag = setTimeout(() => {
        mainFunction(...args);
      }, wait);
    };
  }

  sanitizeModName(aName) {
    // Do not change to "mod-" for backwards compatibility
    return `theme-${aName?.replaceAll(WHITESPACE_RE, "-")?.replaceAll(NON_NAME_RE, "")}`;
  }

  get updatePref() {
    return "harbor.mods.updated-value-observer";
  }

  get modsRootPath() {
    return PathUtils.join(PathUtils.profileDir, "chrome", "harbor-themes");
  }

  get modsDataFile() {
    return PathUtils.join(PathUtils.profileDir, "harbor-themes.json");
  }

  getModFolder(modId) {
    return PathUtils.join(this.modsRootPath, modId);
  }

  async getMods() {
    if (!(await IOUtils.exists(this.modsDataFile))) {
      await IOUtils.writeJSON(this.modsDataFile, {});

      return {};
    }

    let mods = {};

    try {
      mods = await IOUtils.readJSON(this.modsDataFile);

      if (mods === null || typeof mods !== "object") {
        throw new Error("Mods data file is invalid");
      }
    } catch {
      // If we have a corrupted file, reset it
      await IOUtils.writeJSON(this.modsDataFile, {});

      Services.wm
        .getMostRecentWindow("navigator:browser")
        .gHarborUIManager.showToast("harbor-themes-corrupted", {
          timeout: 8000,
        });
    }

    return mods;
  }

  async getModPreferences(mod) {
    const modPath = PathUtils.join(
      this.modsRootPath,
      mod.id,
      "preferences.json"
    );

    if (!(await IOUtils.exists(modPath)) || !mod.preferences) {
      return [];
    }

    try {
      const preferences = await IOUtils.readJSON(modPath);

      return preferences.filter(({ disabledOn = [] }) => {
        return !disabledOn.includes(
          gHarborOperatingSystemCommonUtils.currentOperatingSystem
        );
      });
    } catch (e) {
      console.error(
        `[HarborMods]: Error reading mod preferences for ${mod.name}:`,
        e
      );
      return [];
    }
  }

  async init() {
    try {
      await SessionStore.promiseInitialized;

      if (
        Services.prefs.getBoolPref("harbor.themes.disable-all", false) ||
        Services.appinfo.inSafeMode
      ) {
        console.warn("[HarborMods]: Mods disabled by user or in safe mode.");
        return;
      }

      await this.getMods(); // Check for any errors in the themes data file
      const mods = await this.#getEnabledMods();

      const modsWithPreferences = await Promise.all(
        mods.map(async mod => {
          const preferences = await this.getModPreferences(mod);

          return {
            name: mod.name,
            enabled: mod.enabled,
            preferences,
          };
        })
      );

      this.#writeToDom(modsWithPreferences);

      await this.#insertStylesheet();

      this.#setNewMilestoneIfNeeded();
      if (this.#shouldAutoUpdate()) {
        requestIdleCallback(
          () => {
            if (!window.closed) {
              requestAnimationFrame(() => {
                this.checkForModsUpdates();
              });
            }
          },
          { timeout: 1000 }
        );
      }
    } catch (e) {
      console.error("[HarborMods]: Error loading Harbor Mods:", e);
    }

    const rebuildObserver = this.#rebuildModsStylesheet.bind(this);
    const disableObserver = this.#handleDisableMods.bind(this);
    Services.prefs.addObserver(this.updatePref, rebuildObserver);
    Services.prefs.addObserver("harbor.themes.disable-all", disableObserver);
    window.addEventListener(
      "unload",
      () => {
        Services.prefs.removeObserver(this.updatePref, rebuildObserver);
        Services.prefs.removeObserver(
          "harbor.themes.disable-all",
          disableObserver
        );
      },
      { once: true }
    );
  }

  #setNewMilestoneIfNeeded() {
    const previousMilestone = Services.prefs.getStringPref(
      "harbor.mods.milestone",
      ""
    );
    if (previousMilestone != Services.appinfo.version) {
      Services.prefs.setStringPref(
        "harbor.mods.milestone",
        Services.appinfo.version
      );
      Services.prefs.clearUserPref("harbor.mods.last-update");
    }
  }

  #shouldAutoUpdate() {
    const daysBeforeUpdate = Services.prefs.getIntPref(
      "harbor.mods.auto-update-days"
    );
    const lastUpdatedSec = Services.prefs.getIntPref(
      "harbor.mods.last-update",
      -1
    );
    const nowSec = Math.floor(Date.now() / 1000);
    const daysSinceUpdate = (nowSec - lastUpdatedSec) / (60 * 60 * 24);

    return (
      (Services.prefs.getBoolPref("harbor.mods.auto-update", true) &&
        daysSinceUpdate >= daysBeforeUpdate) ||
      lastUpdatedSec < 0
    );
  }

  async checkForModsUpdates() {
    const mods = await this.getMods();

    const updates = await Promise.all(
      Object.values(mods).map(async currentMod => {
        try {
          const possibleNewModVersion = await this.requestMod(currentMod.id);

          if (!possibleNewModVersion) {
            return null;
          }

          if (
            !this.#compareVersions(
              possibleNewModVersion.version,
              currentMod.version ?? "0.0.0"
            ) &&
            possibleNewModVersion.version != currentMod.version
          ) {
            console.warn(
              `[HarborMods]: Mod update found for mod ${currentMod.name} (${currentMod.id}), current: ${currentMod.version}, new: ${possibleNewModVersion.version}`
            );

            possibleNewModVersion.enabled = currentMod.enabled;

            await this.removeMod(currentMod.id, false);

            mods[currentMod.id] = possibleNewModVersion;

            return possibleNewModVersion;
          }

          return null;
        } catch (e) {
          console.error("[HarborMods]: Error checking for mod updates", e);

          return null;
        }
      })
    );

    await this.updateMods(mods);
    Services.prefs.setIntPref(
      "harbor.mods.last-update",
      Math.floor(Date.now() / 1000)
    );
    return updates.filter(update => {
      return update !== null;
    });
  }

  async removeMod(modId, triggerUpdate = true) {
    const modPath = this.getModFolder(modId);

    console.warn(`[HarborMods]: Removing mod ${modPath}`);

    await IOUtils.remove(modPath, { recursive: true, ignoreAbsent: true });

    const mods = await this.getMods();

    delete mods[modId];

    await IOUtils.writeJSON(this.modsDataFile, mods);

    if (triggerUpdate) {
      this.triggerModsUpdate();
    }
  }

  async enableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[HarborMods]: Enabling mod ${mod.name}`);

    mod.enabled = true;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async disableMod(modId) {
    const mods = await this.getMods();
    const mod = mods[modId];

    console.warn(`[HarborMods]: Disabling mod ${mod.name}`);

    mod.enabled = false;

    await IOUtils.writeJSON(this.modsDataFile, mods);
  }

  async updateMods(mods = undefined) {
    if (!mods) {
      mods = await this.getMods();
    }

    await IOUtils.writeJSON(this.modsDataFile, mods);
    await this.checkForModChanges();
  }

  triggerModsUpdate() {
    Services.prefs.setBoolPref(
      this.updatePref,
      !Services.prefs.getBoolPref(this.updatePref)
    );
  }

  async installMod(mod) {
    try {
      const modPath = PathUtils.join(this.modsRootPath, mod.id);
      await IOUtils.makeDirectory(modPath, { ignoreExisting: true });

      await this.#downloadUrlToFile(
        mod.style,
        PathUtils.join(modPath, "chrome.css")
      );
      await this.#downloadUrlToFile(
        mod.readme,
        PathUtils.join(modPath, "readme.md")
      );

      if (mod.preferences) {
        await this.#downloadUrlToFile(
          mod.preferences,
          PathUtils.join(modPath, "preferences.json")
        );
      }
    } catch (e) {
      console.error("[HarborMods]: Error installing mod", mod.id, e);
    }
  }

  async checkForModChanges() {
    const mods = await this.getMods();

    for (const [modId, mod] of Object.entries(mods)) {
      try {
        if (!mod) {
          continue;
        }

        if (!(await IOUtils.exists(this.getModFolder(modId)))) {
          await this.installMod(mod);
        }
      } catch (e) {
        console.error("[HarborMods]: Error checking for mod changes", e);
      }
    }

    this.triggerModsUpdate();
  }

  get storeBaseUrl() {
    const url = Services.prefs
      .getStringPref("harbor.mods.store-url", "")
      .trim()
      .replace(/\/+$/, "");
    return url || BUNDLED_STORE_URL;
  }

  /**
   * Lists the mods the store offers.
   *
   * @returns {Promise<object[]>} Entries of { id, name, description, author,
   *   version, tags }.
   */
  async getStoreCatalog() {
    const url = `${this.storeBaseUrl}/index.json`;
    if (!this.#isAllowedStoreUrl(url)) {
      throw new Error(`[HarborMods]: Refusing mod store URL: ${url}`);
    }
    const response = await fetch(url, { credentials: "omit" });
    if (!response.ok) {
      throw new Error(`[HarborMods]: Mod store answered ${response.status}`);
    }
    const catalog = await response.json();
    if (!Array.isArray(catalog?.mods)) {
      throw new Error("[HarborMods]: Mod store catalog is invalid");
    }
    return catalog.mods.filter(
      mod => MOD_ID_RE.test(mod?.id ?? "") && typeof mod.name === "string"
    );
  }

  async installModFromStore(modId) {
    const mod = await this.requestMod(modId);
    if (!mod) {
      throw new Error(`[HarborMods]: Mod ${modId} is not in the store`);
    }
    mod.enabled = true;

    const mods = await this.getMods();
    mods[mod.id] = mod;
    await this.updateMods(mods);
    return mod;
  }

  async uninstallMod(modId) {
    await this.removeMod(modId, false);
    await this.updateMods();
  }

  async requestMod(modId) {
    const url = this.#composeModApiUrl(modId);
    if (!this.#isAllowedStoreUrl(url)) {
      throw new Error(`[HarborMods]: Refusing mod store URL: ${url}`);
    }

    console.warn(`[HarborMods]: Fetching mod ${modId} info from ${url}`);

    const data = await fetch(url, { credentials: "omit" });

    if (data.ok) {
      try {
        const obj = await data.json();
        if (typeof obj?.style !== "string" || typeof obj.name !== "string") {
          throw new Error("manifest has no name or style");
        }

        // The folder on disk and the entry in the mods file are keyed by
        // the id we asked for, whatever the manifest claims.
        obj.id = modId;
        // Manifests may point at their assets relatively.
        for (const key of MOD_ASSET_KEYS) {
          if (typeof obj[key] === "string" && obj[key]) {
            obj[key] = new URL(obj[key], url).href;
          }
        }

        return obj;
      } catch (e) {
        console.error(`[HarborMods]: Error parsing mod ${modId} info:`, e);
      }
    } else {
      console.error(
        `[HarborMods]: Error fetching mod ${modId} info:`,
        data.status
      );
    }

    return null;
  }

  async isModInstalled(modId) {
    const mods = await this.getMods();
    return Boolean(mods?.[modId]);
  }

  // public properties end
}

window.gHarborMods = new nsHarborMods();
