# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{03d900f7-639f-4c81-b029-2883dd893ccb}',
        'interfaces': ['nsIHarborMouseTracker'],
        'contract_ids': ['@mozilla.org/harbor/mouse-tracker;1'],
        'type': 'harbor::HarborMouseTracker',
        'headers': ['mozilla/HarborMouseTracker.h'],
        'processes': ProcessSelector.MAIN_PROCESS_ONLY,
    },
]
